version: "3.9"
services:
  tabio:
    container_name: "Tabio"
    ports:
      - '0.0.0.0:8810:80'
    volumes:
      - './models:/app/tabio/models'
      - '../shared_data:/data'
    environment:
      - LOG_LEVEL=info
      - MAX_WORKERS=4
    build:
      context: ./
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
