version: "3.9"
services:
  tabio:
    container_name: "Tabio"
    ports:
      - '0.0.0.0:8810:80'
    volumes:
      - '../tabio_models:/app/tabio/models'
      - '.:/app'
      - '../data:/data'
    environment:
      - LOG_LEVEL=info
      - MAX_WORKERS=1
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /start-reload.sh

